blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/twsl/lit-wsl/discussions/new
    about: Ask and answer questions
  - name: Read the documentation
    url: https://twsl.github.io/lit-wsl/
